name: dashed_line
description: Draw dashed lines with any shape and style you want. Just like that.
version: 0.1.0+3
repository: https://github.com/leancodepl/dashed_line

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  svg_path_parser: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^5.0.0
