name: dashed_line
description: A new Flutter package project.
version: 0.1.0
repository: https://github.com/leancodepl/dashed_line

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  svg_path_parser: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
