name: Test

on:
  push:
    branches: [main]
    tags-ignore: ['v*']
  pull_request:
    branches: [main]

jobs:
  test:
    name: Flutter ${{ matrix.flutter }}

    strategy:
      fail-fast: false
      matrix:
        flutter: ['3.10.x']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter }}

      - name: flutter pub get
        run: flutter pub get

      - name: flutter test
        if: success() || failure()
        run: flutter test --coverage

      - name: flutter analyze
        if: success() || failure()
        run: flutter analyze

      - name: dart format
        if: success() || failure()
        run: dart format --set-exit-if-changed .
